### PR TITLE
FittedCloud storage driver

### PR DESCRIPTION
**Pull request by jack-fittedcloud**
### FittedCloud [EBS Optimizer](http://www.fittedcloud.com/solutions/aws-ebs-optimization/) driver
This driver implements thin-provisioned EBS volumes.

### CODE REVIEW

**Comment by akutz** [comment]
Hi @jack-fittedcloud,

Thank you for this PR. I've enjoyed our chats via e-mail up this point, so I look forward to working with you and your team to get this PR merged and into an upcoming release of libStorage and REX-Ray.

**Comment by akutz** [comment]
Hi @jack-fittedcloud,

Have you validated this driver with your own internal testing?

**Comment by jack-fittedcloud** [comment]
Hi @akutz,

Yes, we have.  We also ran the fittedcloud.test.

**Comment by jack-fittedcloud** [comment]
This doc should give a better idea of how to use it:  [FittedCloud EBS Driver Technical Preview ](https://docs.google.com/document/d/1OXNZjROPo8nmiFmPXtAamrphG47rrU-WATd3uCTe0wU/edit?usp=sharing)

**Comment by akutz** [comment]
Hi @jack-fittedcloud,

Honestly...this looks good. Want to be part of the upcoming libStorage 0.5.0 and REX-Ray 0.80 releases? We need you to rebase this onto the libStorage branch `release/0.5.0` if so, and once you do that, please re-run your tests and paste the resulting output and emitted coverage file from `-test.cover` or `-cover` into a Gist as two files and link them here.

If everything is fine after that I want to merge you into `release/0.5.0` so you can be part of LS 0.5.0-rc2.

**Comment by akutz** [comment]
Hi @jack-fittedcloud,

FYI, please be aware there was one breaking change to a `StorageDriver` function's signature -- `VolumeRemove`. You can read more about it in #409.

**Comment by jack-fittedcloud** [comment]
Thanks @akutz.  I'll be right on it.

**Comment by akutz** [comment]
Hi @jack-fittedcloud,

Please squash this branch.

**Comment by akutz** [comment]
Hi @jack-fittedcloud,

To help you squash your branch and update it to reflect the changes I already mentioned above (since your branch still fails to build due to a lack of the aforesuggested signature refactor) I created [a branch](https://github.com/akutz/libstorage/commits/feature/fittedcloud) with your PR. Please just reset your PR's branch to match mine by doing the following:

```bash
# add my repo as a remote
git remote add kutz https://github.com/akutz/libstorage.git

# fetch my repo
git fetch kutz

# make sure you're on the correct branch
git checkout fittedcloud

# reset the your branch to the tip of mine
git reset --hard kutz/feature/fittedcloud
```

A few notes on which I was being a little lenient, but having rebased your PR and taken a second look I'd like to ask you to handle these items:

* The branch name should follow GitFlow or GitHubFlow per [our developer docs](http://libstorage.readthedocs.io/en/stable/dev-guide/project-guidelines/#submitting-changes), and thus be `feature/fittedcloud`. 
* The column width of source files should be limited to 80 characters.
* The storage driver should *not ever* be invoking the executor. The executor is local only and the storage driver is executed remotely, not on the clients.
* A commit's message (and a PR's description) should be useful. See how I updated your original commit message:
```
FittedCloud storage driver

This patch adds support for the FittedCloud storage driver. FittedCloud
provides dynamic sizing and optimization of EBS volumes. More
information about FittedCloud is available at
http://www.fittedcloud.com/.
```
For more information on writing commit messages please see [this page](http://libstorage.readthedocs.io/en/stable/dev-guide/project-guidelines/#commit-messages) in the libStorage developer documentation.

**Comment by jack-fittedcloud** [comment]
Hi @akutz,

Sorry I shouldn't have pushed the code yesterday since I was not done.  Thanks for your comments.  I will work on them today.

The reason I called the executor was to get the next available device name because in our case we might have multiple volumes constituting a fittedcloud optimized volume.  To attach those volumes I need to find the next available device names.  I can change it so that it's local to the storage driver.

**Comment by akutz** [comment]
Hi Jack,

The next device name is part of the attach ops args though. It's sent via the API call.

-- 
-a

**Comment by jack-fittedcloud** [comment]
In our case, a Docker volume maps to one or more EBS volumes, depending on the used size of the Docker volume.  The next device passed in to the VolumeAttach call is merely one of the constituent EBS volumes carrying the volume name in the "Name" tag.  Fittedcloud storage driver then have to attach all EBS volumes carrying the same "Name" tag, as well as the "FittedCloudCreated" tag.  This is currently done locally to the storage driver, which I realized means we can't support remote storage server in this version.  Our plan is to support that in the next version so we can have something useful for people to start using. Does that make sense?

**Comment by akutz** [comment]
Hi @jack-fittedcloud,

RE: support. Hmm...What do you need today to support remote? The ability to pass more than one next device value or the ability to do a one-to-many mapping for Docker vols to EBS vols?

**Comment by jack-fittedcloud** [comment]
@akutz, it's not that.  The existing Docker/REX-Ray abstraction makes sense.  
When we started working on this project we saw pretty close matches between the storage driver's volume operations and our Agent's, therefore we chose to integrate our logic into the driver.  This worked out quite well so far until we looked at the remote storage server support.  In our case, volume operations (create/attach/detach/remove) are initiated by our Agents which sit right on each host, not a remote server.  To support remote I imagine I will need to move logic to the "client" (the executor?)  Honestly I don't yet have a clear picture of how it should be done.  Thoughts?

**Comment by akutz** [comment]
Hi @jack-fittedcloud,

I'm going to respond to you via e-mail.

**Comment by jack-fittedcloud** [comment]
fittedcloud.test 
[output](https://gist.github.com/jack-fittedcloud/6642599c55d88b48ca407d6ca60eb941)
[-test.coverprofile emitted coverage file](https://gist.github.com/jack-fittedcloud/1e5c0521a270aaf2d9d0b766f863b282)

**Comment by jack-fittedcloud** [comment]
Hi @akutz,

Is there a tool I can use to format the source file width to 80 chars?  Also, how do I rename my PR's branch to feature/fittedcloud?  Should I close this one and create a new PR?

**Comment by akutz** [comment]
Hi @jack-fittedcloud,

There's no tool to format the width of the source files. I just do that manually by setting a gutter in Atom. As for the branch name, don't worry about it for this PR. Please keep it in mind for the future. Thank you.

**Pull request merged**
