### PR TITLE
Use local device map for attachment device info

### LINKED ISSUE #431: Unable to detach volume in client/server mode
When deploying in a server/client mode (with rexray classic on one node, and rexray-client on another node), a call to `detach` is failing with:

`ERRO[0422] POST https://api.digitalocean.com/v2/volumes/de89b811-f928-11e6-98b3-000f5339d321/actions: 422 Attachment not found  host=tcp://:7979 instanceID=digitalocean=40470784,name=rexray2&region=sfo2 route=volumeDetach server=tin-slave-hm service=digitalocean storageDriver=digitalocean task=0 time=1487791291854 tls=false txCR=1487791289 txID=00cf8769-6e06-45df-6a78-358e52adcd01`

I highly suspect this is because of the use of `StorageActions.Detach()` here: https://github.com/codedellemc/libstorage/blob/release/0.5.0/drivers/storage/digitalocean/storage/digitalocean_storage.go#L191

The fix is likely to use `StorageActions.DetachByDropletID()` instead, which takes an argument for a dropletID. Seems the `Detach` call always assumes you are detaching from yourself.  This implies this driver has not been tested in a client/server environment. Might find more still...

server version
```
root@rexray1:~# rexray -l warn version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.8.0-rc1
OsArch: Linux-x86_64
Branch: v0.8.0-rc1
Commit: 483caefe9a904163daaf82c74a7652254415fce5
Formed: Tue, 21 Feb 2017 20:15:45 UTC

libStorage
----------
SemVer: 0.5.0-rc2
OsArch: Linux-x86_64
Branch: v0.8.0-rc1
Commit: 4a1b372134e27da77bbfa109ad5dac0e9499fbc4
Formed: Tue, 21 Feb 2017 20:14:29 UTC
```

server config
```
root@rexray1:~# cat /etc/rexray/config.yml
rexray:
  logLevel: debug
libstorage:
  host: tcp://127.0.0.1:7979
  embedded: true
  service: digitalocean
  server:
    endpoints:
      public:
        address: tcp://:7979
    services:
      digitalocean:
        driver: digitalocean
digitalocean:
  token: XXXXXX
  region: sfo2
```

client version:
```
root@rexray2:~# rexray-client version
REX-Ray
-------
Binary: /usr/bin/rexray-client
Flavor: client
SemVer: 0.8.0-rc1
OsArch: Linux-x86_64
Branch: v0.8.0-rc1
Commit: 483caefe9a904163daaf82c74a7652254415fce5
Formed: Tue, 21 Feb 2017 20:14:52 UTC

libStorage
----------
SemVer: 0.5.0-rc2
OsArch: Linux-x86_64
Branch: v0.8.0-rc1
Commit: 4a1b372134e27da77bbfa109ad5dac0e9499fbc4
Formed: Tue, 21 Feb 2017 20:14:39 UTC
```

client config
```
root@rexray2:~# cat /etc/rexray/config.yml
libstorage:
  host: tcp://<rexray1 IP>:7979
  service: digitalocean
```

### LINKED ISSUE #432: local device lookup does not work in client/server mode
The digital ocean driver is assuming its running on the same node as the client. This causes local device maps to fail.

This is best evidenced by this: https://github.com/codedellemc/libstorage/blob/release/0.5.0/drivers/storage/digitalocean/storage/digitalocean_storage.go#L318-L323

When it tries to look up the device name, it’s looking at the local file system instead of the local Device map supplied by the client.

If this driver is really going into 0.5, we'll need to document that it does not work for client/server deployments, and that preemption does not work (because of #431).

### PR DESCRIPTION
**Pull request by codenrhoden**
This patch changes the dobs driver to use the client-provided local
device map when looking up device info. Previously the driver was
assuming that it had local access to the device, but the required info
is actually provided by the client. This allows the the driver to work
in server/client mode.

Fixes #432 

I can also confirm that when running this patch, I did not run into the issues outlined in #431. We had previously thought that perhaps #431 was never real, and was only a transient error. However, there are still community reports of it happening.

Cleaned up a few linter items, and made sure everything used `ctx` for logging instead of `log`.

### CODE REVIEW

**Comment by codenrhoden** [comment]
Here is some output showing things working. `rexray2` is configured to point to `rexray1` as a libStorage server. Previously, the device lookups (done with `ls --path`) did not work in client/server mode.  This log also shows that attach/detach works in client/server.

And, I also did pre-emption from `rexray1`, and that worked as well.

```
[root@rexray2 ~]# ./rexray volume create test2 --size 5
ID                                    Name   Status     Size
c821ea56-14aa-11e7-bbff-0242ac110106  test2  available  5
[root@rexray2 ~]# ./rexray volume attach test2
ID                                    Name   Status    Size
c821ea56-14aa-11e7-bbff-0242ac110106  test2  attached  5
[root@rexray2 ~]# ./rexray volume ls --format jsonp --path
[
  {
    "attachments": [
      {
        "deviceName": "/dev/sda",
        "instanceID": {
          "id": "44101051",
          "driver": "dobs",
          "service": ""
        },
        "status": "",
        "volumeID": "c821ea56-14aa-11e7-bbff-0242ac110106"
      }
    ],
    "attachmentState": 2,
    "availabilityZone": "sfo2",
    "name": "test2",
    "size": 5,
    "id": "c821ea56-14aa-11e7-bbff-0242ac110106",
    "type": "",
    "Path": ""
  }
][root@rexray2 ~]# ./rexray volume ls --format jsonp
[
  {
    "attachments": [
      {
        "deviceName": "",
        "instanceID": {
          "id": "44101051",
          "driver": "dobs",
          "service": ""
        },
        "status": "",
        "volumeID": "c821ea56-14aa-11e7-bbff-0242ac110106"
      }
    ],
    "attachmentState": 2,
    "availabilityZone": "sfo2",
    "name": "test2",
    "size": 5,
    "id": "c821ea56-14aa-11e7-bbff-0242ac110106",
    "type": ""
  },
  {
    "attachments": [
      {
        "deviceName": "",
        "instanceID": {
          "id": "44101050",
          "driver": "dobs",
          "service": ""
        },
        "status": "",
        "volumeID": "f79bf08e-14a9-11e7-a01d-0242ac11060b"
      }
    ],
    "attachmentState": 4,
    "availabilityZone": "sfo2",
    "name": "test",
    "size": 1,
    "id": "f79bf08e-14a9-11e7-a01d-0242ac11060b",
    "type": ""
  }
][root@rexray2 ~]# ./rexray volume ls
ID                                    Name   Status       Size
f79bf08e-14a9-11e7-a01d-0242ac11060b  test   unavailable  1
c821ea56-14aa-11e7-bbff-0242ac110106  test2  attached     5
[root@rexray2 ~]# ./rexray volume detach test2
ID                                    Name   Status     Size
c821ea56-14aa-11e7-bbff-0242ac110106  test2  available  5
```

**Comment by codenrhoden** [comment]
@akutz this one is rebased and ready to go.

**Comment by codenrhoden** [comment]
EDIT: I originally had this PR closing #431 as well, but due to community reports of that still happening, I have removed that from the PR description.

**Comment by akutz** [comment]
Hi @codenrhoden,

So merge or not?

**Comment by codenrhoden** [comment]
@akutz Absolutely merge. It fixes #432.

**Comment by klausenbusk** [comment]
> EDIT: I originally had this PR closing #431 as well, but due to community reports of that still happening, I have removed that from the PR description.

I finally managed to reproduce this:
> I think I have found a way to reproduce this. It seems like detach stop working after the volume has been attached to more than 1 droplet.
> 
> See script: https://gist.github.com/klausenbusk/d5b6455d3253a2b0575e151719a0d12b
> 
> Could you try attaching 6d43bc3c-1576-11e7-914d-0242ac111807 to another droplet and then see if detach is still working?

Maybe we should switch to `DetachByDropletID` until this is fixed, I'm not sure how fast DO is gonna respond.

**Pull request merged**
