### PR TITLE
Build Support for arm/arm64

### PR DESCRIPTION
**Pull request by akutz**
This patch (related to codedellemc/rexray#860) updates the Makefile to support building libStorage for the arm and arm64 architectures. From now on executor binaries that follow the pattern `lsx-GOOS` will have an implicit architecture of amd64. However, executor binaries can now also follow the pattern `lsx-GOOS-GOARCH` in order to support non-amd64 architectures.

### CODE REVIEW

**Comment by ghost** [comment]
Wow, good job @akutz. One big step for ARM!

**Comment by akutz** [comment]
Thanks! I still need to update the libStorage client code to request an executor with the GOARCH if not amd64, and I've been trying to get a rpi qemu env online to test the changes.

**Comment by akutz** [comment]
Hi @naster01,

I can confirm the `arm` executor does indeed work:

### Printing the System Architecture
```bash
$ uname -a
Linux retropie 4.4.26-v7+ #915 SMP Thu Oct 20 17:08:44 BST 2016 armv7l GNU/Linux
```

### Running `lsx-linux-arm`
```bash
$ ./lsx-linux-arm 
usage: ./lsx-linux-arm <executor> supported
                                  instanceID
                                  nextDevice
                                  localDevices <scanType>
                                  wait <scanType> <attachToken> <timeout>
                                  mounts
                                  mount [-l label] [-o options] device path
                                  umount path

       executor:    vfs

       scanType:    0,quick | 1,deep

       attachToken: <token>

       timeout:     30s | 1h | 5m
```

**Comment by ghost** [comment]
I think I'm building with the correct requirements [build-ref](https://libstorage.readthedocs.io/en/stable/dev-guide/build-reference/).
```
OS : Linux dnode1 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
Docker ver : 17.05.0-ce
Docker API : 1.29
GNU Make : 4.0
Git : 2.1.4
```
```
naster@dnode1:~/Sources/libstorage $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

Are there any args?
```
naster@dnode1:~/Sources/libstorage $ sudo make
make docker-build
make[1]: Entering directory '/home/naster/Sources/libstorage'
Error response from daemon: Container 41b589a0074dfb20cea48997e3dc7e36b4b08895799db43efdeed7ca6cc0890c is not running
Makefile:215: recipe for target 'docker-init' failed
make[1]: *** [docker-init] Error 1
make[1]: Leaving directory '/home/naster/Sources/libstorage'
Makefile:30: recipe for target 'all' failed
make: *** [all] Error 2

```
```
naster@dnode1:~/Sources/libstorage $ sudo GOOS=linux GOARCH=arm64 make
make docker-build
make[1]: Entering directory '/home/naster/Sources/libstorage'
Error response from daemon: Container 41b589a0074dfb20cea48997e3dc7e36b4b08895799db43efdeed7ca6cc0890c is not running
Makefile:215: recipe for target 'docker-init' failed
make[1]: *** [docker-init] Error 1
make[1]: Leaving directory '/home/naster/Sources/libstorage'
Makefile:30: recipe for target 'all' failed
make: *** [all] Error 2
```

Syslog 
```
May 29 18:41:48 dnode1 dockerd[728]: time="2017-05-29T18:41:48.194841858Z" level=error msg="Error setting up exec command in container build-libstorage: Container 41b589a0074dfb20cea48997e3dc7e36b4b08895$
May 29 18:41:48 dnode1 dockerd[728]: time="2017-05-29T18:41:48.195051857Z" level=error msg="Handler for POST /v1.29/containers/build-libstorage/exec returned error: Container 41b589a0074dfb20cea48997e3dc$
```
Docker logs
```
standard_init_linux.go:178: exec user process caused "exec format error"
```

Well I'm gonna wait for bins or rexray's docker plugin I think.

**Comment by akutz** [comment]
Hi @naster01,

You're building outside of a `GOPATH`, and that isn't supported when building Go programs. However, since you're using Docker it should be fine. Look at the reported error:

> Error response from daemon: Container 41b589a0074dfb20cea48997e3dc7e36b4b08895799db43efdeed7ca6cc0890c is not running

You've got an old container that is stopped and preventing the build. Use the `docker-clobber` [target](https://libstorage.readthedocs.io/en/stable/dev-guide/build-reference/#basic-build-targets) from the documentation to clean up stale containers.

Also, you're setting `GOOS` and `GOARCH`, but those are not the correct values to set for the Docker build. I again refer you to the [documentation](https://libstorage.readthedocs.io/en/stable/dev-guide/build-reference/#basic-build-options) for build options.

**Pull request merged**
