### PR TITLE
vbox: fix Supported() when using dmesg

### PR DESCRIPTION
**Pull request by codenrhoden**
Reported by @h0tbird, the virtualbox executor was not working on CoreOS. More specifically, it was returning Supported = false, because it was not correctly parsing output from `dmesg`.

Any Linux distro that does not have the `dmidecode` command in its `$PATH` would experience the same issue.

### CODE REVIEW

**Comment by akutz** [comment]
Hi @codenrhoden,

I just updated this PR to point to the `release/0.3.3` branch. I'll be rebuilding this PR for tests as soon as the release branch is updated from master.

**Comment by akutz** [comment]
Hi @codenrhoden,

Would you please force-push this branch again to trigger a new build against the updated merge target? Thanks.

**Comment by codenrhoden** [comment]
Done.

Annoying, a force-push wouldn't do it, as it just said "already up to date". I actually had to force it to have a new commit ID so it would push a change. Anyways, test is running...

**Comment by akutz** [comment]
Ah, yeah. You have to do a `git commit --amend -C HEAD` to do it. I have this mapped to a few aliases (see `git amend` and `git resend` in my `$HOME/.gitconfig`:

```
[alias]
    comp = !sh -c 'git rev-list $1 | grep $2' -
    r = reset --hard @{u}
    m = merge --ff-only
    b = !git branch --list | grep '^*' | awk '{print $2}'
    pu = push -u origin
    du = diff @{u}
    su = status -u no
    co = checkout
    br = branch
    ci = commit
    new-patch = format-patch --stdout
    unstage = reset HEAD --
    last = log -1 HEAD
    lc = log ORIG_HEAD.. --stat --no-merges
    undo = reset --hard
    prune-all = !git remote | xargs -n 1 git remote prune
    lg = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
    lgf = "!f() { git lg --all --author=$1; }; f"
    first = !sh -c 'git log `git rev-list --max-parents=0 HEAD`'
    serve = daemon --reuseaddr --verbose --enable=upload-pack --enable=upload-archive --enable=receive-pack --base-path=. --export-all ./.git
    conflict = !git status --porcelain | grep UU | tr -d 'UU '
    l = log --stat --abbrev-commit --pretty=oneline --graph -t  --cc
    h = log --oneline --abbrev-commit --branches=* --graph --decorate
    lp = log --unified=3 --abbrev-commit --date=relative
    lpw = log --unified=1 --abbrev-commit --date=relative --color-words
    lo = log --oneline
    st = status
    lt = tag --sort=-v:refname
    amend = !"git commit --amend --date=\"$(date)\" -C HEAD"
    resend = !git amend && git push --force
    resend-all = !git add -u && git amend && git push --force
    rm-merged = !git branch --merged master | grep -v '* master' | xargs -n 1 git branch -d
    ls-origin = !git branch -r | grep origin | grep -iv master | cut -c10-
    ls-origin-merged = !git branch -r --merged | grep origin | grep -iv master | cut -c10-
    reset-master = !git fetch upstream && git checkout master && git reset --hard upstream/master && git push origin
[push]
    default = current
[rerere]
    enabled = true
```

See above. You should also make sure your `rerere` setting is enabled. [Rerere](https://git-scm.com/blog/2010/03/08/rerere.html) is the most important git configuration about which most developers have no clue.

**Pull request merged**
